controller_list:
  - name: indy10_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
